# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
# warnings_are_errors: false

before_install:
  - sudo apt-get install libgsl23 libgslcblas0 libgsl0-dev

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr
  - cran/gsl
#  - o1iv3r/ClustImpute

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master
